import turtle
window = turtle.Screen()
my_turtle = turtle.Turtle()
window.bgcolor("white")
my_turtle.color("Slategrey")
my_turtle.pencolor("black")
my_turtle.forward(100)
my_turtle.right(144)
my_turtle.forward(100)
my_turtle.right(144)
my_turtle.forward(100)
my_turtle.right(144)
my_turtle.forward(100)
my_turtle.right(144)
my_turtle.forward(100)
my_turtle.right(144)
my_turtle.color("Lightskyblue")
my_turtle.penup()
my_turtle.goto(0, -2)
my_turtle.pendown()
my_turtle.forward(200)
my_turtle.right(144)
my_turtle.forward(200)
my_turtle.right(144)
my_turtle.forward(200)
my_turtle.right(144)
my_turtle.forward(200)
my_turtle.right(144)
my_turtle.forward(200)
my_turtle.right(144)
window.exitonclick()

